22 create a decorator for restricting amount of time a function can be called
Dawid64/decorify pull request #29
Opened 2024-11-24 15:14 UTC by Dawid64

Added requested decorator ending #22

2024-11-24 17:06 UTC, adamtms approved these changes
Looks good.
But, I have an idea for an optional improvement.
In most cases number of API calls is tracked using tumbling windows not slididing windows and these windows are the same for all users. e.g. if you can send 100 request per hours, you could send 100 requests between 5:50-5:59 and then additional 100 between 6:01-6:10.
We can always add this as a feature later.

2024-11-24 20:43 UTC, Dawid64 commented
> you could send 100 requests between 5:50-5:59 and then additional 100 between 6:01-6:10.
I applied with 2 versions, syncing to clock, to do mentioned functionality, and slightly fast - creating start of interval at the beginning of function

2024-11-24 21:50 UTC, adamtms requested changes

2024-11-24 21:50 UTC, adamtms commented on decorify/basic.py
> +        __func__.__interval_number = (now.hour * 360 + now.minute * 60 + now.second) // time
Shouldnt it be 3600 instead of 360?

2024-11-24 21:50 UTC, adamtms commented on decorify/basic.py
I am also wondering whether we want to look at the clock or just find interval number from timestamp, current solution can kind of break if we pass e.g. 24h. However it is and edge case I dont know why would anyone use this function then

2024-11-24 22:16 UTC, Dawid64 commented on decorify/basic.py
I will add time, and I will leave a note not to use it for over 14 days

2024-11-24 22:26 UTC, Dawid64 commented on decorify/basic.py
I found even better and simpler way for that, now it should not only be much quicker, but it also removes upper bound.

2024-11-24 22:37 UTC, adamtms commented on decorify/basic.py
yea it looks much simpler.

2024-12-07 00:39 UTC, JaszczurGra approved these changes
Not tested

2024-12-07 00:41 UTC, merged